"""Removendo nome unico

Revision ID: 5888bab5e472
Revises: 5755273b604a
Create Date: 2025-11-09 18:46:03.226495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5888bab5e472'
down_revision: Union[str, Sequence[str], None] = '5755273b604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=1)
    # ### end Alembic commands ###
